# network architecture
# encoder related
etype: bgrup     # encoder architecture type
elayers: 3
eunits: 128
eprojs: 128
subsample: "1_2_2_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 1
dunits: 256
# attention related
atype: location
adim: 256
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.5

# minibatch related
batch-size: 10
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced
sortagrad: 0

# optimization related
opt: adadelta
epochs: 40
patience: 3

# scheduled sampling option
sampling-probability: 1.0
dropout-rate: 0.2
dropout-rate-decoder: 0.1
