# network architecture
# encoder related
etype: blstmp     # encoder architecture type
elayers: 5
eunits: 512
eprojs: 512
subsample: "1_2_2_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 1
dunits: 512
# attention related
atype: location
adim: 512
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.5

# minibatch related
batch-size: 30
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# other config
dropout-rate: 0.2
lsm-weight: 0.1
weight-decay: 1e-6

# optimization related
opt: adadelta
epochs: 40
patience: 3

# scheduled sampling option
sampling-probability: 0.2
