# network architecture
# encoder related
etype: vggblstmp     # encoder architecture type
elayers: 5
eunits: 512
eprojs: 512
subsample: "1_1_1_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 2
dunits: 512
# attention related
atype: coverage_location
adim: 512
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.0

# minibatch related
batch-size: 10
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
opt: adadelta
epochs: 40
patience: 3

# scheduled sampling option
sampling-probability: 0.0
dropout-rate: 0.2