cp conf/base.yaml conf/train_kld_square_no_decay.yaml
cp conf/base.yaml conf/train_kld_impulse_no_decay.yaml
cp conf/base.yaml conf/train_kld_gaussian_no_decay.yaml
cp conf/base.yaml conf/train_kld_square_yes_decay.yaml
cp conf/base.yaml conf/train_kld_impulse_yes_decay.yaml
cp conf/base.yaml conf/train_kld_gaussian_yes_decay.yaml
cp conf/base.yaml conf/train_cosine_square_no_decay.yaml
cp conf/base.yaml conf/train_cosine_impulse_no_decay.yaml
cp conf/base.yaml conf/train_cosine_gaussian_no_decay.yaml
cp conf/base.yaml conf/train_cosine_square_yes_decay.yaml
cp conf/base.yaml conf/train_cosine_impulse_yes_decay.yaml
cp conf/base.yaml conf/train_cosine_gaussian_yes_decay.yaml
cp conf/base.yaml conf/train_sinkhorn_square_no_decay.yaml
cp conf/base.yaml conf/train_sinkhorn_impulse_no_decay.yaml
cp conf/base.yaml conf/train_sinkhorn_gaussian_no_decay.yaml
cp conf/base.yaml conf/train_sinkhorn_square_yes_decay.yaml
cp conf/base.yaml conf/train_sinkhorn_impulse_yes_decay.yaml
cp conf/base.yaml conf/train_sinkhorn_gaussian_yes_decay.yaml