#!/bin/bash
# THIS FILE IS GENERATED BY tools/setup_anaconda.sh
if [ -z "${PS1:-}" ]; then
    PS1=__dummy__
fi
. /home/neo/espnet/tools/venv/etc/profile.d/conda.sh && conda deactivate && conda activate 
