# network architecture
# encoder related
etype: blstmp     # encoder architecture type
elayers: 3
eunits: 320
eprojs: 320
subsample: "1_1_1_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 1
dunits: 320
# attention related
atype: location
adim: 320
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.5

# minibatch related
batch-size: 10
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
opt: adadelta
epochs: 1
patience: 3

# scheduled sampling option
sampling-probability: 0.2
dropout-rate: 0.2

tap-enc-senone: 1
tap-enc-phn: 2

oracle-w: 1.0
oracle-stop: 40

oracle-w-decay: False
alignment-type: square
alignment-loss-type: cosine