aconv-chans: 10
aconv-filts: 100
adim: 1
atype: dot
batch-size: 10
dlayers: 1
dropout-rate: 0.2
dropout-rate-decoder: 0.1
dunits: 320
elayers: 4
epochs: 40
eprojs: 320
etype: blstmp
eunits: 320
maxlen-in: 800
maxlen-out: 150
mtlalpha: 0.5
opt: adadelta
patience: 3
sampling-probability: 0.3
sortagrad: 0
subsample: '1_2_2_1_1'
