# network architecture
# encoder related
etype: dnn     # encoder architecture type
elayers: 1
eunits: 320
eprojs: 100
subsample: "1_2_2_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 3
dunits: 300
# attention related
atype: dot
adim: 100
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.5

# minibatch related
batch-size: 5
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
opt: adadelta
epochs: 20
patience: 8

# scheduled sampling option
sampling-probability: 0.1
